{"error":"Speech recognition service unavailable","timestamp":"2025-06-20T05:11:30.437Z","message":"STT failed after 2 attempts. Last error: Whisper process failed with code 1: Using device: cpu\n\nA module that was compiled using NumPy 1.x cannot be run in\nNumPy 2.1.2 as it may crash. To support both 1.x and 2.x\nversions of NumPy, modules must be compiled with NumPy 2.0.\nSome module may need to rebuild instead e.g. with 'pybind11>=2.12'.\n\nIf you are a user of the module, the easiest solution will be to\ndowngrade to 'numpy<2' or try to upgrade the affected module.\nWe expect that some modules will need time to support NumPy 2.\n\nTraceback (most recent call last):  File \"<string>\", line 38, in <module>\n  File \"<string>\", line 14, in main\n  File \"/usr/local/lib/python3.10/dist-packages/whisper/__init__.py\", line 150, in load_model\n    checkpoint = torch.load(fp, map_location=device)\n  File \"/usr/local/lib/python3.10/dist-packages/torch/serialization.py\", line 809, in load\n    return _load(opened_zipfile, map_location, pickle_module, **pickle_load_args)\n  File \"/usr/local/lib/python3.10/dist-packages/torch/serialization.py\", line 1172, in _load\n    result = unpickler.load()\n  File \"/usr/local/lib/python3.10/dist-packages/torch/_utils.py\", line 169, in _rebuild_tensor_v2\n    tensor = _rebuild_tensor(storage, storage_offset, size, stride)\n  File \"/usr/local/lib/python3.10/dist-packages/torch/_utils.py\", line 147, in _rebuild_tensor\n    t = torch.tensor([], dtype=storage.dtype, device=storage._untyped_storage.device)\n/usr/local/lib/python3.10/dist-packages/torch/_utils.py:147: UserWarning: Failed to initialize NumPy: _ARRAY_API not found (Triggered internally at /root/pytorch/torch/csrc/utils/tensor_numpy.cpp:84.)\n  t = torch.tensor([], dtype=storage.dtype, device=storage._untyped_storage.device)\n","code":"EXTERNAL_API_ERROR"}